CreationDate = 2022-12-13T13:10:23.333646

[charuco]
columns = 4
rows = 5
board_height = 11
board_width = 8.5
dictionary = "DICT_4X4_50"
units = "inch"
aruco_scale = 0.75
square_size_overide_cm = 5.4
inverted = false
