CreationDate = 2022-12-12T13:14:20.080680

[cam_0]
port = 0
resolution = [ 640, 480,]
rotation_count = 0
exposure = -6.0
grid_count = 0

[cam_1]
port = 1
resolution = [ 1024, 576,]
rotation_count = 0
exposure = -6.0
grid_count = 0

[charuco]
columns = 4
rows = 5
board_height = 11.0
board_width = 8.5
dictionary = "DICT_4X4_1000"
units = "inch"
aruco_scale = 0.75
square_size_overide_cm = 5.25
inverted = true
